### ISSUE TITLE
"make install" places nonfunctional pdb2pka in apbs-3.0.0/../pdb2pqr

### ISSUE THREAD

**Issue by mathog** [Electrostatics/apbs#70]
When "make install" runs it does these two commands (in log file on lines 313 and 314):

```
cd /usr/common/src/apbs-3.0.0/build/tools/python && /home/common/src/cmake-3.17.1/bin/cmake -E copy /usr/common/src/apbs-3.0.0/build/tools/python/apbslib.py /usr/common/src/apbs-3.0.0/../pdb2pqr/pdb2pka
cd /usr/common/src/apbs-3.0.0/build/tools/python && /home/common/src/cmake-3.17.1/bin/cmake -E copy /usr/common/src/apbs-3.0.0/build/lib/_apbslib.so /usr/common/src/apbs-3.0.0/../pdb2pqr/pdb2pka

```
These result in a directory /usr/common/src/pdb2pqr which contains the single file pdb2pka.  That is a binary dynamically linked to many libraries including libPBSAMLib but NOT the Intel MKL libraries:

```
module load apbs # so it can find all the libraries apbs built
ldd pdb2pka
        linux-vdso.so.1 (0x00007ffdcb0f8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f84a57f4000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f84a545f000)
        libTABIPBlib.so => /usr/common/src/apbs-3.0.0/build/bem-prefix/src/bem-build/libTABIPBlib.so (0x00007f84a524b000)
        libmaloc.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libmaloc.so.1 (0x00007f84a4fc8000)
        libamd.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libamd.so.1 (0x00007f84a4dbf000)
        libpunc.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libpunc.so.1 (0x00007f84a4bbd000)
        libmc.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libmc.so.1 (0x00007f84a4943000)
        libgamer.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libgamer.so.1 (0x00007f84a4721000)
        libsuperlu.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libsuperlu.so.1 (0x00007f84a44d3000)
        libumfpack.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libumfpack.so.1 (0x00007f84a4227000)
        libblas.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libblas.so.1 (0x00007f84a3fb9000)
        libvf2c.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libvf2c.so.1 (0x00007f84a3d9b000)
        libtetgen.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libtetgen.so.1 (0x00007f84a3b18000)
        libtriangle.so.1 => /usr/common/src/apbs-3.0.0/build/fetk/lib/libtriangle.so.1 (0x00007f84a38f6000)
        libreadline.so.7 => /lib64/libreadline.so.7 (0x00007f84a36a7000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f84a347a000)
        libGeometricFlowLib.so => /usr/common/src/apbs-3.0.0/build/geoflow-prefix/src/geoflow-build/lib/libGeometricFlowLib.so (0x00007f84a3260000)
        libPBAMLib.so => /usr/common/src/apbs-3.0.0/build/pbam-prefix/src/pbam-build/pbam/src/libPBAMLib.so (0x00007f84a2fa7000)
        libPBSAMLib.so => /usr/common/src/apbs-3.0.0/build/pbsam-prefix/src/pbsam-build/pbsam/src/libPBSAMLib.so (0x00007f84a2c81000)
        libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007f84a0fe8000)
        libapbs_mg.so => /usr/common/src/apbs-3.0.0/build/lib/libapbs_mg.so (0x00007f84a0dbf000)
        libapbs_fem.so => /usr/common/src/apbs-3.0.0/build/lib/libapbs_fem.so (0x00007f84a0bac000)
        libapbs_routines.so => /usr/common/src/apbs-3.0.0/build/lib/libapbs_routines.so (0x00007f84a0992000)
        libpython3.6m.so.1.0 => /lib64/libpython3.6m.so.1.0 (0x00007f84a0447000)
        libapbs_generic.so => /usr/common/src/apbs-3.0.0/build/lib/libapbs_generic.so (0x00007f84a0214000)
        libapbs_pmgc.so => /usr/common/src/apbs-3.0.0/build/lib/libapbs_pmgc.so (0x00007f849ffe5000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f849fc23000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f84a5d95000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f849fa0b000)
        libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007f849f58e000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f849f0ab000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f849ee8b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f849ec87000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f849ea83000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f849e842000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f849e62b000)

```

This binary segfaults when run, here in strace:

```
strace ./pdb2pka
execve("./pdb2pka", ["./pdb2pka"], 0x7ffc549d0260 /* 75 vars */) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by intendo** [comment]
This is part of the build problems we are having with MacOS and Linux where the dynamically linked libraries are point to the "build" directory and not the "installed" directory. We are working through this problem this week and hopefully will get the root cause of this problem solved.

**Comment by sobolevnrm** [comment]
We've also separated the PDB2PQR-related (including PDB2PKA) functionality into a separate repository to make it a bit easier to troubleshoot issues like this.

**Comment by intendo** [comment]
I believe this is addressed in @nsoblath new build for APBS and will be in the next release.

**Comment by BJWiley233** [comment]
I was able to install with both Clang (after doing some manipulation of the inline stuff) and icc and was able to compile with python bindings.  I also saw that `apbslib.py` was copied  `pdb2pqr/pdb2pka` which I also cannot run.  In addition apbslib.py from the `build/tools/python` directory was not copied into the install directory.  I copied it over but still don't think it works as I get:

```
% python main.py
Traceback (most recent call last):
  File "/usr/local/apbs/share/apbs/tools/python/main.py", line 60, in <module>
    from apbslib import (
  File "/usr/local/apbs/share/apbs/tools/python/apbslib.py", line 15, in <module>
    import _apbslib
ModuleNotFoundError: No module named '_apbslib'
```
